name: Docker build and push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2
    - name: Running on the default branch.
      if: steps.branch-name.outputs.is_default == 'true'
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
        ls
        docker build . --tag cs3mesh/cs3apis4lab:latest
        docker push cs3mesh/cs3apis4lab:latest

    - name: Running on a pull request branch.
      if: steps.branch-name.outputs.is_default == 'false'
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
        ls
        docker build . --tag cs3mesh/cs3apis4lab:${{ steps.branch-name.outputs.current_branch }}
        docker push cs3mesh/cs3apis4lab:${{ steps.branch-name.outputs.current_branch }}

